version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./public:/var/www/public
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./storage/app/public:/var/www/storage/app/public
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app

  node:
    image: node:14-alpine
    container_name: node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: ["yarn", "run", "watch"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
